### ISSUE TITLE
is there a way to create a vpn connection with "Send all traffic over VPN connection" unchecked?

### ISSUE THREAD

**Issue by cswilliams** [halo/macosvpn#12]
Hi,

I was curious if there was a way to create a vpn with the "Send all traffic over VPN connection" unchecked? Every vpn connection that I create always has this option checked.  I didn't see anything in the arguments to configure this.

Thanks,
Chris

**Comment by ensons** [comment]
Hi! Now, there's a good feature request :) I didn't even think about this, so there is no option at the moment in the command line.

Technically, it's as simple as [removing this line](https://github.com/halo/macosvpn/blob/e0b74551c281b7f96755d92717bf71cb195fa1cf/macosvpn/Classes/VPNServiceConfig.m#L98) and there should be a `--no-force-traffic` option or something (do you have a good naming suggestion?).

If I'll find the time coming week I can give it a try. You don't happen to speak Objective-C, do you? ;)

**Comment by halo** [comment]
Ah, used the wrong account to post the previous comment, changing it...

**Comment by halo** [comment]
Didn't find time for this yet, sorry.

**Comment by steve-jansen** [comment]
FYI #14 is my attempt to implement this.  Apologies if I broke any conventions - my obj-c skills are rusty at best :smile:
