### ISSUE TITLE
Homebrew formula?

### ISSUE THREAD

**Issue by MatzFan** [halo/macosvpn#16]
Just come across your tool - which is exactly what I am looking for. It seems to not be available via Homebrew - is there a reason for that & if not would you have any objection to me writing a formula for it?

**Comment by halo** [comment]
It would be my greatest honor to have it in homebrew. Let me know if I can be of assistance, other than that, please proceed :D

**Comment by MatzFan** [comment]
Cool - thought as much, I'll get on the case 😀

**Comment by MatzFan** [comment]
OK, so first hurdle is Homebrew like to build from source and [don't like binaries](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md). Can you provide configure/compile instructions on how to do this from your your tar.gz files & any dependancies? I'll progress it over the weekend..

**Comment by halo** [comment]
Well, if the Xcode tools is installed, it is as simple as typing `xcodebuild` in the Terminal when located in the directory of this repository. After about 10 seconds, the executable is located inside the repository in the directory `build/Release/macosvpn`.

But I'm not sure what the homebrew conventions are for this. A quick google revealed [this](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/graphviz.rb#L36) and [this](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/graphviz.rb#L90). That's probably the way to go.

**Comment by MatzFan** [comment]
Understood. So I don't have full Xcode, just it's Command Line Tool's (as do many brew users I think) so can't test a formula that has full Xcode as a dependancy 😞. If it can be complied with make, gcc or other Xcode CLT's let me know how & I'll finish the formula.

**Comment by halo** [comment]
Ah, so you have the "Xcode command line tools"? As far as I know that should be enough to compile it.

**Comment by MatzFan** [comment]
AFAIK ```xcodebuild``` needs full Xcode:
```
$ xcodebuild
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```

**Comment by halo** [comment]
Bummer. There must be dozens of homebrew projects using this though. I just haven't investigated yet how they do it.

**Comment by MatzFan** [comment]
Doubtless. If I ever feel the need to get full Xcode I'll revisit this. In the meantime thanks for the very useful code.

**Comment by MatzFan** [comment]
**Update**: As of today ```brew install macosvpn``` is a thing. It is barebones but works - wasn't that hard to write in the end. I specified Xcode >= 6.1, as that seems to be what your Travis build uses.

**Comment by halo** [comment]
Don't know what to say, I'm going to use it myself! :) Thank you indeed.
