### ISSUE TITLE
Write permission error when app is trying to add keychains

### ISSUE THREAD

**Issue by callmeflinx** [halo/macosvpn#2]
When `macosvpn`is trying to add keychains in order to store `Password` and `Shared secret` in `VPNKeychain.m line` 115, then in line 120 we have `Creating Keychain item failed: write permissions error`
When i run `macosvpn` with `sudo` all working just great - no errors and VPN connection with keychains are creating.
I know app requiments say that in order to run macosvpn user should have administrator privileges, but is it possible to make app work from unprivileged user's accounts, e.g. app is asking user password (like sudo does) in order to add keychains.  

Mac OSX 10.9.5 Darwin/13.4.0

**Comment by facemovie** [comment]
I am also face this problem...

**Comment by halo** [comment]
Hi @facemovie did you use sudo? Without sudo I don't think there will be any access to the system keychain.

**Comment by facemovie** [comment]
@halo 
Hi, 
  i used sudo yesterday,and it's working. 
Do you have any plan to add GUI on  this project?
Thanks for your reply!

**Comment by halo** [comment]
> Do you have any plan to add GUI on this project?

How would "my" GUI be different from **System Preferences** ➞ **Network**?
