### ISSUE TITLE
macosvpn and 10.12 Beta

### ISSUE THREAD

**Issue by develop2020** [halo/macosvpn#21]
Dear Halo,

I have been using macosvpn with great success to setup Cisco IPSec VPN services. However I am currently testing macOS 10.12 and when I try and use macosvpn to create a Cisco IPSec Service (--cisco) the command produces a Segmentation fault: 11 error and the service is NOT created. However it can create non-Cisco VPN services without the Segmentation fault: 11. 

Are you aware of this issue and do you plan to update the app to work with 10.12?

Thanks very much for your help.

Kind regards,

Gary.

**Comment by halo** [comment]
Hi Gary! Thank you for your helpful report.

I have not tested Sierra yet. That you can create L2TP services is a very good sign. It means that no severe permission-like show-stoppers have been introduced in the new OS that would prohibit creating VPNs altogether. But don't let's cheer too early :)

I'm definitely planning on supporting Sierra and once it's released I will upgrade my OS and see whether I can get macosvpn going again.

What you can try meanwhile is to add the `--debug` flag to your command and see if it always crashes at the same logging message. And also, which message that would be :)

If you feel even more adventurous, go ahead and clone the repo and open it in Xcode to see whether it compiles without warnings. So far, Travis does not have [10.12](https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version) in its environment so I cannot test it there yet.

All the best

**Comment by halo** [comment]
Oh, and you're on the latest `macosvpn --version`, right?

**Comment by develop2020** [comment]
Hello halo,

Thanks for your speedy response. I'm now running the 10.12 GM and I have the same issue. I have checked the version and run with --debug. I've passed the results below. 10.12 is out on the 20/09/2016!

Good luck.

Kind regards,

Gary.

From my terminal, all password etc are of course just for testing:

harley:~ root# macosvpn --version
0.2.1
harley:~ root# 

harley:~ root# macosvpn create --cisco Atlantic --endpoint atlantic.example.com --username Alice --password p4ssw0rd --shared-secret s3same --groupname MyName
  
Segmentation fault: 11
harley:~ root# 


harley:~ root# macosvpn create --debug  --cisco Atlantic --endpoint atlantic.example.com --username Alice --password p4ssw0rd --shared-secret s3same --groupname MyName
  
  You are running in debug mode
  
  Uncaptured argument values: /usr/local/bin/macosvpn
  Uncaptured argument values: /usr/local/bin/macosvpn
  So, you wish to create one or more VPN service(s).
  Gained superhuman rights.
  Creating new Cisco IPSec Service using <[Cisco IPSec] name=Atlantic endpoint=atlantic.example.com username=Alice password=p4ssw0rd sharedSecret=s3same localIdentifier=MyName>
  Cisco IPSec Service detected...
  Instantiating interface references...
  Creating a new, fresh VPN service in memory using the interface we already created
  That service is to have a name
  And we also would like to know the internal ID of this service
Segmentation fault: 11
harley:~ root#

**Comment by develop2020** [comment]
P.S. I've tired this with SIP enabled and disabled. Same result.

**Comment by halo** [comment]
Would you mind giving this release candidate a try?

https://github.com/halo/macosvpn/releases/tag/0.3.0

**Comment by develop2020** [comment]
Hi There, I'm sorry its taken me too long to get back to you. I haven't been working with Sierra for a while. However I'm really pleased to say that this new version works perfectly for IPSEC! Thank you.

**Comment by halo** [comment]
Cool! I will do some cleanup and release the official version when I find some time.

Thank you for reporting and even more for testing the new version :)
