### ISSUE TITLE
Debug the project

### ISSUE THREAD

**Issue by laxmansahni** [halo/macosvpn#29]
Hi,

We run executable from command-line to create VPN. We would like to debug the executable. 
Please tell how to debug in Xcode.

**Comment by halo** [comment]
Hi @laxmansahni 

Could you elaborate a little bit what you mean by debug? Do you mean breakpoints? Do you mean testing? Do you mean static code analysis? Do you mean debugging output?

As for breakpoints or crash reports, have a look at [this comment](https://github.com/halo/macosvpn/issues/13#issuecomment-155133890) which shows how the settings should look like when debugging.

**Comment by laxmansahni** [comment]
We want to add breakpoints.

**Comment by laxmansahni** [comment]
I ran Xcode as sudo and am able to debug. 
# sudo /Applications/Xcode.app/Contents/MacOS/Xcode
