### ISSUE TITLE
Build problems with Xcode 8.3.2

### ISSUE THREAD

**Issue by edonkeycoin** [halo/macosvpn#30]
I'm seeing a number of build issues with Xcode 8.3.2. First, the command line xcodebuild fails because the Swift code needs to be updated.

Next, both Wrap.swift and VPNHelp.swift fail to compile with the following errors:

```
/Users/acronce/Sources/third_party/macosvpn/macosvpn/macosvpn/Vendor/PrettyColors/Wrap.swift:215:50: 'Distance' is not a member type of 'Color.Wrap.Index' (aka 'Int')

/Users/acronce/Sources/third_party/macosvpn/macosvpn/macosvpn/Vendor/PrettyColors/Wrap.swift:192:1: Type 'Color.Wrap' does not conform to protocol '_MutableIndexable'

/Users/acronce/Sources/third_party/macosvpn/macosvpn/macosvpn/Vendor/PrettyColors/Wrap.swift:192:1: Type 'Color.Wrap' does not conform to protocol '_IndexableBase'
```

**Comment by halo** [comment]
Hi! Thanks for reporting the issue. Would you mind testing the [30-xcode832 branch](https://github.com/halo/macosvpn/pull/31)? Looks like it builds and the specs pass on my machine.

**Comment by edonkeycoin** [comment]
Thanks! I checked out the branch and it builds and runs fine. 

Note that I had already worked around the build problems locally by merging in some changes from the latest PrettyColors. But for some reason the output of the help text was not colored.

Anyway,  your branch seems to work much better than my hack job. Thanks again for the quick response.

**Comment by halo** [comment]
> I checked out the branch and it builds and runs fine.

I noticed that most of the output was polluted with a lot of `Optional("..")` messages which were introduced in the latest Swift. I fixed that as well now.

>  Thanks again for the quick response.

Thank **you** :)

I merged the changes into master but did not release a new version, since this is only internal developer stuff and does not affect users of the compiled version in any way.
