### ISSUE TITLE
Enable Session Options

### ISSUE THREAD

**Issue by blackthroat** [halo/macosvpn#33]
Not sure if I missed this somewhere or if this would be considered a feature request, but is it possible to enable both Disconnect options when creating the VPN configuration?

![image](https://user-images.githubusercontent.com/25038086/29475928-61c06692-8427-11e7-8193-5fccbf310c80.png)

**Comment by halo** [comment]
Hi! Thank you for your report! You didn't miss it, it's just something nobody requested. It should not be so difficult. Within the next few weeks I will hopefully find the time to look into it. Please ping me again if you don't hear from me in, say, 20 days. Thanks!

**Comment by halo** [comment]
@blackthroat Please give it a try: https://github.com/halo/macosvpn/releases/tag/0.3.2

I tested it manually and the integration specs are passing, so if it works fine for you, I'll publish the pre-release as official release.

Thank you for your time!

**Comment by blackthroat** [comment]
Just tested it and it worked as expected. Thanks a bunch for the work and the quick turn-around!!

**Comment by halo** [comment]
Thank you for trying it out! I'm glad it works - I obviously spent too much time in that crazy API given how quickly I found out how to implement that feature :D
