### ISSUE TITLE
Delete all VPN entries at once

### ISSUE THREAD

**Issue by TechArea** [halo/macosvpn#38]
I miss the feature to remove all VPN entries at once.
Can you please add that function?

For ex.
macosvpn delete --all
macosvpn delete -a

or whatever...

Thanks in advance

**Comment by halo** [comment]
I like the idea! I will implement it once I find the time. My guess is a week or two.

**Comment by halo** [comment]
Alas, I was a little bit too optimistic. I'm using outdated third-party code and I would have to upgrade all that to Swift first. 

So, unfortunately I cannot do this in any quick and dirty manner and it requires quite some time. Sorry.

**Comment by TechArea** [comment]
Don't worry. We can wait few weeks. :-)

**Comment by halo** [comment]
I have two questions:

1. What is your use-case exactly that you'd want to delete all VPN services? I'm curious about how this app is used.
2. Is it not easier/more flexible for you to use IKEv2 VPN configurations (.mobileconfig) instead? (I'm not sure why so many people still use L2TP and IPSec)

Thank you!

**Comment by TechArea** [comment]
1. I'm managing a few destinations with dyndns and unfortunately macOS has an issue there. If the IP changed recently and didn't update your DNS server, you've to delete the whole VPN entry and add it again or wait a few hours. But usually I can't wait few hours. So what I'm doing? I'm deleting all VPN connections, because I've so many of them, that it's not practicable to search for a specific, because macOS don't sort them by A-Z.

2. IPSec because of Cisco ASA 5505 and similar... for ex.

**Comment by halo** [comment]
Hi, how exactly should this feature work?

* `macosvpn delete --all`
* `macosvpn delete --ipsec --all`
* `macosvpn delete --l2tp --name London --name Sydney`

One of those? All of those? :)

**Comment by TechArea** [comment]
`macosvpn delete --all` should be enough (for my purpose), but feel free to add some easter eggs :-D

**Comment by halo** [comment]
> you've to delete the whole VPN entry and add it again

By the way, can this not be achieved already using the `--force` flag? I assume that you know the names of the VPN services you want to delete and then re-create?

**Comment by TechArea** [comment]
That's what I'm doing right now, because of missing "delete" function.
I've few VPN's and it takes double of time amount to do an import when I'm using the --force flag.
It's not the end of the world if it wouldn't be possible to implement this feature, but it would half the time for an import.

**Comment by halo** [comment]
Hi, I just wanted to let you know that I [implemented your feature here](https://github.com/halo/macosvpn/commit/26fda33f91de4d83716797240856b2f6c65bb017#diff-a2d3165c2ae85041776ac0301acd8e24) but you'll need a little more patience until I can officially release a new version. I need to improve tests and make sure everything works 100%.

**Comment by halo** [comment]
Would you mind trying it out? I recommend that you clone and build the project yourself using Xcode 11. Alternatively, you can download the executable here:

https://github.com/halo/macosvpn/releases/download/1.0.0.beta2/macosvpn.zip

**Comment by TechArea** [comment]
It works like a charm! (Finished without errors)

**Comment by TechArea** [comment]
Deleting works.
But my old script doesn't work anymore...

Unknown arguments: -oceupsg XXXXXXXXXXXX

**Comment by halo** [comment]
> Deleting works.

Nice!

> But my old script doesn't work anymore...
> Unknown arguments: -oceupsg XXXXXXXXXXXX

I had to replace the 3rd-party library that was responsible for parsing the command line argument. The new library does not support such a syntax. You will have to start using `-c XXX -u XXX`. 

(Since the `-oceupsg` syntax was somewhat unusual anyway, I'm OK with that breaking change. Sorry for the inconvenience, though :)

If it's OK with you, I'll close this issue and refer to https://github.com/halo/macosvpn/issues/41 instead. Now I just need some beta-testers and if no bugs turn up, it will be officially released.

Thank you for reporting and thanks for trying it out. I'm glad it works not only on my machine ;)
