### ISSUE TITLE
precompiled macosvpn fails on 10.13

### ISSUE THREAD

**Issue by mattip-** [halo/macosvpn#45]
Hi ,

on High Sierra your precompiled binary does not seem to work
```
$sudo /usr/local/bin/macosvpn --version 
dyld: Library not loaded: @rpath/libswiftCore.dylib
Referenced from: /usr/local/bin/macosvpn
Reason: image not found
Abort trap: 6
```
and trying to build an own version on High Sierra  fails as well. 

```
$ brew install macosvpn
macosvpn: A full installation of Xcode.app 11.1 is required to compile
this software. Installing just the Command Line Tools is not sufficient.

Xcode 11.1 cannot be installed on macOS 10.13.
You must upgrade your version of macOS.
Error: An unsatisfied requirement failed this build.
```

**Comment by halo** [comment]
Hi!

Where did you get the binary from? One of the [releases](https://github.com/halo/macosvpn/releases)? Which one?

As for brew, I never really took the time to dig into the versioning. [This sha](https://github.com/tiiiecherle/homebrew-core/blob/7caa43224eda0f126b9cf5703548d9d5dc8e366e/Formula/macosvpn.rb#L10) for example, I'm not sure how it works.

Also, there would have to be multiple Xcode versione [here](https://github.com/tiiiecherle/homebrew-core/blob/7caa43224eda0f126b9cf5703548d9d5dc8e366e/Formula/macosvpn.rb#L15) for compatibility with different macOS versions.

If anyone would find the time to improve the homebrew formula, I'd be grateful. I'm rather confident that the git tags I maintained in my repo here work, as long as you take the right one.

Lastly, I'm really not sure how far back the latest binary is backwards compatible. What Xcode says in the build configuration apparently does not correspond to reality :|

**Comment by mattip-** [comment]
Hi,

I simply followed your instruction so I guess I got the Version 1.0

Will do some experiments with the older releases  - we want to use your tool to mass deploy VPN Settings  so a universally running binary would be appreciated but I may be able to modify the installer so that the proper version will be installed.

I stil have to fiddle around with the order of network services .

Putting a VPN config to the first position is nessecary  to be able to use the internal DNS servers

Thanks a lot for your swift feedback!

Matthias

Am 07.03.2020 um 19:21 schrieb halo <notifications@github.com>:

**Comment by mattip-** [comment]
I can confirm the precompiled version 0.35 works on HighSierra. So it may be useful to modify the  "Requirements" section in your ReadMe a little. 
Anyway: thanks a lot for your work and the quick support!

**Comment by halo** [comment]
> So it may be useful to modify the "Requirements" section in your ReadMe a little.

I did that now, thank you for pointing it out :)
