### ISSUE TITLE
VPN setup requires sudo

### ISSUE THREAD

**Issue by akanesato3nets** [halo/macosvpn#54]
@halo 
Without sudo, can I create VPN in MacOS?
It seems like it is requiring sudo permission to write to System Keychain which is not necessary for network VPN setup.
What should I do to use this without sudo permission?

**Comment by halo** [comment]
Hi! You cannot create a cisco or l2tp VPN service in macOS without sudo.

The VPN credentials (password/secret key) are stored in the system keychain.
You need sudo to write to the system keychain.

What makes you think you can create VPN service without administrator privileges?

**Comment by akanesato3nets** [comment]
Because in windows, I could create VPN connection without admin permission.
In MacOS, would it be the same?

**Comment by halo** [comment]
I'm not sure how Windows stores and retrieves the passwords internally. 

In macOS you do need administrator privileges to access the System Keychain.

**Comment by akanesato3nets** [comment]
@halo 
Thank you for your clarification.
One more question.
I checked this on Monterey (version 12.1).
Which version does this support?

**Comment by halo** [comment]
That's actually a good question. It definitely works on Big Sur (macOS 11) and usually it works on macOS versions that were just released. I don't have Monterey at the moment, so I cannot guarantee you that it should work.

**Comment by Machinas** [comment]
I can confirm that it works on Monterey up to 12.2! Great project! One comment on-topic: when you create a VPN connection "by hand" via the GUI, the system does not ask for the user password for elevation. Perhaps there is an "agent" running that is used by the GUI for that scenario, eliminating the need for sudo.

**Comment by fortiko** [comment]
I can confirm that it works on Monterey up to 12.2! Great project! One comment on-topic: when you create a VPN connection "by hand" via the GUI, the system does not ask for the user password for elevation. Perhaps there is an "agent" running that is used by the GUI for that scenario, eliminating the need for sudo.

**Comment by halo** [comment]
Yes, that's a good point, I noticed. GUI applications can, upon installation, persist an agent (these are called "privileged helper"). I use that technique in [this project](https://github.com/halo/LinkLiar#development) to change the MAC addresses of interfaces (in the graphic in the README; notice the interplay between `LinkLiar`, `LinkHelper` and `linkdaemon`).

This doesn't exist for command line applications, however. As far as I know, anyway. And you would still need sudo the first time it is used. So, there is not so much gain if `macosvpn` is mainly used for remote configuration of computers. Good point, though!
