### ISSUE TITLE
No way to define GroupName in Cisco VPN 

### ISSUE THREAD

**Issue by arnieggertsson** [halo/macosvpn#7]

**Comment by halo** [comment]
Ah, I knew the day would come ;) I'll see if I find time for this soon. Thank you for your comment! You're not possibly interested in programming this yourself? :D

**Comment by arnieggertsson** [comment]
;)   I'll give it a try and get back to you,

**Comment by arnieggertsson** [comment]
I have just tried to commit an update to the project to fix the issue.  it is similar to the one you reference,

**Comment by halo** [comment]
Hi! You cannot push to my account. Instead, you click on the ["Fork"](https://help.github.com/articles/fork-a-repo/) button in the top right of this very page. That will clone the entire repository to your own Github account. There you create a branch and make the code changes. Once you're happy with the code, you can create a pull request in your branch. I will then be able to review the pull request and merge it into my repository.

See also [this help](https://help.github.com/articles/using-pull-requests/) and if you're new to git, you might want to try the [desktop application](https://desktop.github.com).
